### ISSUE TITLE
Serial interface successfully connects then immediately disconnects

### ISSUE THREAD

**Issue by mkalin2** [OpenC3/cosmos#1085]
Environment: 
    Podman
    RHEL8
    COSMOS v5.13.0

I have a plugin with and interface called ENCODER_INT defined as seen below:
```
plugin.txt:

# Set VARIABLEs here to allow variation in your plugin

VARIABLE encoder_target_name ENCODER

TARGET ENCODER <%= encoder_target_name %>
INTERFACE <%= encoder_target_name %>_INT serial_interface.rb /dev/ttyUSB0 /dev/ttyUSB0 115200 NONE 1 5 5 TEMPLATE 0x0D 0x0D
  MAP_TARGET <%= encoder_target_name %>
```

It maps to a target called ENCODER which currently has not been configured past being generated by the target generator. I am currently just trying to make sure I can get devices connected to COSMOS.

When I build and run the plugin I see the following happen in the command log:
![image](https://github.com/OpenC3/cosmos/assets/159323793/47ff0536-0e8d-433a-a3fa-eba09009d062)

The encoder interface continuously connects and then immediately disconnects. It will do this forever unless I hit the disconnect button.

How can I debug this issue? I had previously tried configuring the target and creating a set of commands and telemetry but this issue still occurred. 

It seems like its trying to read data that's not there and then disconnecting as a result?

**Comment by jmthomas** [comment]
Have you mapped the serial port in the compose file? See https://docs.openc3.com/docs/guides/bridges#note-on-serial-ports

```
   devices:
     - "/dev/ttyUSB0:/dev/ttyUSB0"

```

**Comment by mkalin2** [comment]
Yes, I followed those instructions in the Bridge documentation. Previously I didn't have the port mapped and was getting an error about the port not existing. After updating compose.yaml and the r/w permissions this new issue started happening.

Here is what the operator service looks like in compose.yaml:
```
  openc3-operator:
    user: "${OPENC3_USER_ID:-1001}:${OPENC3_GROUP_ID:-1001}"
    image: "${OPENC3_REGISTRY}/${OPENC3_NAMESPACE}/openc3-operator${OPENC3_IMAGE_SUFFIX}:${OPENC3_TAG}"
    restart: "unless-stopped"
    # ports:
    #  - "127.0.0.1:7779:7779" # Open port for the demo router
    depends_on:
      - "openc3-redis"
      - "openc3-redis-ephemeral"
      - "openc3-minio"
    volumes:
      - "openc3-gems-v:/gems:ro"
      - "./plugins:/plugins:z"
      - "./cacert.pem:/devel/cacert.pem:z"
      # Add access to the entire C drive on Windows
      # - "/c:/c"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      GEM_HOME: "/gems"
      PYTHONUSERBASE: "/gems/python_packages"
      OPENC3_REDIS_USERNAME: "${OPENC3_REDIS_USERNAME}"
      OPENC3_REDIS_PASSWORD: "${OPENC3_REDIS_PASSWORD}"
      OPENC3_BUCKET_USERNAME: "${OPENC3_BUCKET_USERNAME}"
      OPENC3_BUCKET_PASSWORD: "${OPENC3_BUCKET_PASSWORD}"
      OPENC3_SERVICE_PASSWORD: "${OPENC3_SERVICE_PASSWORD}"
    env_file:
      - ".env"
    extra_hosts:
      - host.docker.internal:host-gateway
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
```
