### ISSUE TITLE
Prometheus uses yml instead of yaml

### ISSUE THREAD

**Issue by MTI-twalker** [OpenC3/cosmos#485]
In your documentation it states:
https://openc3.com/docs/v5/monitoring#prometheus
prometheus.yaml

Based on the prometheus documentation, it only recognizes .yml
https://prometheus.io/docs/prometheus/latest/installation/#custom-image

I was unable to bring up the custom configuration without that file name.

Additionally in the .yml file that is in the documentation. The targets lines need to be updated with the new container names. I added "-cosmos" after "openc3".

I was able to get the targets loaded but then I saw that it could not connect. So it might be worth mentioning to add the prometheus container to the cosmos docker network. 
These were the commands I ran:
```
docker build -t my-prometheus .
docker run -p 9090:9090 --network openc3-cosmos-network my-prometheus
```

I was able to get prometheus to recognize the targets but found that the minio had a forbidden error. 
![image](https://user-images.githubusercontent.com/101339004/219210368-2e58b8d4-3a72-4bb3-bd76-fb2a6de4e797.png)

I dug into the 404 error a bit and found that the minio has a 307 redirect to http://openc3.com/minio. Which then returns the 404 error. I am not sure if that is what was intended or if something changed in the latest minio? Maybe the link for /minio/v2/metrics/cluster has been updated? Could we use wherever this http://localhost:2900/minio/tools/metrics redirects internally?

In regards to adding it to the network, I noticed that if I brought down OpenC3 while the prometheus container (which I attached to the network) also went down because stopping removes the network. In this case, it was a lot easier to add prometheus to the openc3 build due to the dependency. So I suggest maybe adding a folder ./Prometheus to your cosmos-project. 
Adding in the Dockerfile:
```
FROM prom/prometheus:v2.24.1
ADD prometheus.yml /etc/prometheus/
```
Adding in prometheus.yml:
```
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: openc3-internal-metrics
    metrics_path: "/openc3-api/internal/metrics"
    static_configs:
      - targets: ["openc3-cosmos-cmd-tlm-api:2901"]

  - job_name: openc3-cmd-tlm-api
    metrics_path: "/openc3-api/metrics"
    static_configs:
      - targets: ["openc3-cosmos-cmd-tlm-api:2901"]

  - job_name: openc3-script-runner-api
    metrics_path: "/script-api/metrics"
    static_configs:
      - targets: ["openc3-cosmos-script-runner-api:2902"]

  - job_name: minio-job
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
    - targets: ['openc3-minio:9000']
```
Then updating the compose.yaml file with this:
```

  prometheus:
    build: ./Prometheus
    image: my-prometheus
    ports:
      - "9090:9090"
    restart: "unless-stopped"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
```

That way the container comes up with cosmos attached to the network. Might be worth including that in the documents, or to the main project?
